version: 2
archives:
  - name_template: "{{.Binary}}_{{.Os}}_{{.Arch}}"
    format_overrides:
    - goos: windows
      format: zip
builds:
  - main: ./main.go
    id: "cmd"
    binary: batesul
    goos:
      - linux
      - windows
    goarch:
      - amd64
